"""empty message

Revision ID: f8f1b5996c75
Revises: a0afcb7a8f5e
Create Date: 2017-12-05 15:04:06.242992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8f1b5996c75'
down_revision = 'a0afcb7a8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apscheduler_jobs', 'next_run_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('user_task', sa.Column('task', sa.NullType(), nullable=False))
    op.create_foreign_key(None, 'user_task', 'apscheduler_jobs', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task', type_='foreignkey')
    op.drop_column('user_task', 'task')
    op.alter_column('apscheduler_jobs', 'next_run_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
